AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWSConfigReporting

  Sample SAM Template for AWSConfigReporting

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ConfigDataPrepFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda_code/
      Handler: AWSConfigDataPrepare.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          SOURCE_BUCKET: "aws_config"
          DESTINATION_BUCKET: "awsconfig_reporting"
      Architectures:
        - x86_64
      Events:
        ScheduledFunction:
          Type: Schedule
          Properties:
              Schedule: cron(0 12 * * ? *)
              Enabled: True



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  HelloWorldFunction:
    Description: "Data Preparation Lambda Function ARN"
    Value: !GetAtt ConfigDataPrepFunction.Arn

